require("config.basic")
require("config.lazy")
require("config.icons")
require("config.keybindings")
require("config.plugins.lualine")
require("config.plugins.dashboard")
vim.cmd("colorscheme dayfox")