require("config.basic")
require("config.keybindings")
require("config.lazy")
require("config.icons")
require("config.plugins.dashboard")
require("config.plugins.neoscroll")
vim.cmd("colorscheme dayfox")